### ISSUE TITLE
Enh: provide a docker-compose.yml file

### ISSUE THREAD

**Issue by flefevre** [plaggy/fast-whisper-server#2]
Thanks for the work done.
Will you be able to provide a docker-compose.yml file with the gpu configuration

```
services:
  fasterdia:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fasterdia
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      #- whispercache:/root/.cache/whisper
      #- ./models:/root/.cache/whisper
    environment:
      - TZ=Europe/Paris
      - ASR_MODEL=${ASR_MODEL}
      - ASR_ENGINE=${ASR_ENGINE}
      - DIARIZATION_MODEL=pyannote/speaker-diarization-3.1
      - ASSISTANT_MODEL=distil-whisper/distil-large-v3
      - HF_TOKEN=hf_XXXXX
    labels:
      - traefik.enable=true
      - traefik.http.routers.fasterdia.rule=Host(`fasterdia.${DOMAIN}`)
      - traefik.http.routers.fasterdia.tls=true
      - traefik.http.services.fasterdia.loadbalancer.server.port=7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```
